import {
  ElButton,
  ElCol,
  ElRow,
  ElAvatar,
  ElContainer,
  ElAside,
  ElMenu,
  ElSubmenu,
  ElMenuItemGroup,
  ElMenuItem,
  ElHeader,
  ElDropdown,
  ElDropdownMenu,
  ElDropdownItem,
  ElMain,
  ElTable,
  ElTableColumn,
  ElRadioGroup,
  ElRadioButton,
  ElTabs,
  ElTabPane,
  ElInputNumber,
  ElForm,
  ElFormItem,
  ElInput,
  ElCollapse,
  ElCollapseItem,
  ElSlider,
  ElSwitch,
  ElImage,
  ElLink,
  ElMessage
} from 'element-plus'


export default (app) => {
  app.use(ElButton)
  app.use(ElCol)
  app.use(ElRow)
  app.use(ElAvatar)
  app.use(ElContainer)
  app.use(ElAside)
  app.use(ElMenu)
  app.use(ElSubmenu)
  app.use(ElMenuItemGroup)
  app.use(ElMenuItem)
  app.use(ElHeader)
  app.use(ElDropdown)
  app.use(ElDropdownMenu)
  app.use(ElDropdownItem)
  app.use(ElMain)
  app.use(ElTable)
  app.use(ElTableColumn)
  app.use(ElRadioGroup)
  app.use(ElRadioButton)
  app.use(ElTabs)
  app.use(ElTabPane)
  app.use(ElInputNumber)
  app.use(ElForm)
  app.use(ElFormItem)
  app.use(ElInput)
  app.use(ElCollapse)
  app.use(ElCollapseItem)
  app.use(ElSlider)
  app.use(ElSwitch)
  app.use(ElImage)
  app.use(ElLink)
  app.use(ElMessage)
}
